AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  porteiro

  Sample SAM Template for porteiro
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LigarPorteiro:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: src/handlers/porteiro.startEC2Instance
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        CloudwatchEvent:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Schedule:  cron(50, 10 ?, * MON-FRI *) 
      Policies:
        - Statement:
            - Sid: StartEC2Instance
              Effect: Allow
              Action:
                - ec2:StartInstances
              Resource: "*"
                 


